####
PUT http://127.0.0.1:3000/
content-type: application/json
X-Master-Key: "$2b$10$HsyvwxdxpxbSeGNBElK9jeti8KAhscS4w34erHfLrK0edDcPda7Re"

{
    "user": "aaasiai",
    "message": "eiaaa"
}

###
GET http://127.0.0.1:3000/
